version: '3.8'

volumes:
  pgdata:

services:
  pg:
    image: postgres:9.6
    restart: always
    container_name: pokebuilder-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pokebuilder
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    
