version: '3.8'

services:
  api: 
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:5432/${POSTGRES_DB}?schema=public
    command: npm run start:dev
    ports:
      - "3333:3000"
    depends_on:
      - pg
  pg:
    image: postgres:9.6
    restart: always
    container_name: pokebuilder-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: